config/routes.rb
Rails.application.routes.draw do
  # Root route
  root 'application#index'

  # Session routes
  post 'login', to: 'sessions#create', as: :login
  get 'logout', to: 'sessions#destroy', as: :destroy_session

  # Foursquare routes
  get 'suggestion/foursquare', to: 'foursquare#create_suggestion',
                               as: :foursquare_suggestion,
                               default: { format: 'js' }
  # User routes
  get '/user/new', to: 'user#new', as: :new_user
  post '/user/new', to: 'user#create', as: :create_user
  get '/user/show', to: 'user#show', as: :show_user
  patch 'user/update', to: 'user#update', as: :update_user
  get 'user/favorites', to: 'user#favorites', as: :favorites
  
  #DatePlans routes
  get '/dateplan', to: 'dateplan#show', as: :dateplan

  resources :dateplan
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  first_name :string
#  last_name  :string
#  nickname   :string
#  gender     :string
#  email      :string
#  birthdate  :date
#  password   :string
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  has_many :dateplans, inverse_of: :user
  has_many :interests_users, inverse_of: :user
  has_many :interests, through: :interests_users, inverse_of: :users

  validates :first_name, presence: true
  validates :last_name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: true }
  validates :password_hash, presence: true, on: :update
  validates :password_salt, presence: true, on: :update
  validates :password, presence: true, on: :create,
                       length: { in: 8..20 }

  attr_accessor :password

  before_create :encrypt

  def edit_interests(interest_ids)
    current_interests = self.interests.pluck(:id)
    create_interests(interest_ids - current_interests)
    delete_interests(current_interests - interest_ids)
  end

  private

  def create_interests(interest_ids)
    interest_ids.each do |i_id|
      InterestsUser.create(user_id: self.id, interest_id: i_id)
    end
  end

  def delete_interests(interest_ids)
    delete_interests_instances = interests_users.where(interest_id: interest_ids)
    delete_interests_instances.delete_all
  end

  def encrypt
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	def new
    @user = User.new
	end

	def create
    @user = User.new user_params
    if @user.save
      flash[:succes] = 'You have registered successfuly'
      login_with_new_user
      redirect_to show_user_path
    else
      flash[:error] = 'An error occurred. Please try again.'
      render :new
    end
	end

	def show
    @user = current_user
	end

  def update
    @user = current_user
    interest_ids = params[:user][:interest_ids].delete_if {|id| id.blank?}
    if @user.edit_interests(interest_ids)
      flash[:succes] = 'You edited your interests'
      login_with_new_user
      redirect_to dateplan_path
    else
      flash[:error] = 'An error occurred. Please try again.'
      render :show
    end
  end

  def favorites
    @user = current_user
    @favorites = Dateplan.where(user_id: current_user.id)
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name, :last_name, :nickname, :gender, :email, :password
      )
  end

  def login_with_new_user
    session[:user_id] = @user.id
  end
end

app/views/user/_form.html.slim
= simple_form_for @user, url: create_user_path do |u|
	.col-lg-12
		= u.input :first_name, label: "First Name" 
	.col-lg-12
		= u.input :last_name, label: "Last Name"
	.col-lg-12
		= u.input :nickname, label: "Nickname (optional)"
	.col-lg-12
		= u.input :gender, label: "Gender (optional)"
	.col-lg-12
		= u.input :email, label: "E-mail"
	.col-lg-12
		= u.input :password, type: 'password', label: "Password"
	.col-lg-6.col-lg-offset-1
		= u.submit 'Create', class: 'btn'
		'
		.btn.btn-danger
			= link_to :back
				i.fa.fa-close

app/views/user/_update.html.slim
= simple_form_for @user, url: update_user_path do |u|
	/ .col-lg-6
	/ 	= u.input :first_name, placeholder: "First Name"
	/ .col-lg-6
	/ 	= u.input :last_name, placeholder: "Last Name"
	/ .col-lg-6
	/ 	= u.input :nickname, placeholder: "Nickname (optional)"
	/ .col-lg-6
	/ 	= u.input :gender, placeholder: "Gender (optional)"
	/ .col-lg-6
	/ 	= u.input :email, placeholder: "E-mail"
	/ .col-lg-6
	/ 	= u.input :password, type: 'password', placeholder: "Password"
	.col-lg-12
		#accordion aria-multiselectable="true" role="tablist"  
	    - Category.all.each_with_index do |c, index|
	    	.panel.white-background
			    .panel-heading role="tab" id="heading-#{index}" 
			      h5.panel-title style="color: #9e9e9e !important"
			        a aria-controls="collapse-#{index}" aria-expanded="false" data-parent="#accordion" data-toggle="collapse" href="#collapse-#{index}" 
			          = c.name
			    .panel-collapse.collapse aria-labelledby="heading-#{index}" id="collapse-#{index}" role="tabpanel"
	  				= u.association :interests, collection: Interest.all.where(category_id: c.id), as: :check_boxes, label_method: :description
	.col-lg-12
		= link_to 'Favorites', favorites_path, class: 'btn btn-primary'
	.col-lg-6.col-lg-offset-6
		= u.submit 'Update', class: 'btn btn-primary' 

app/views/user/favorites.html.slim
.container.light-grey-background#favorites-container
  .row.favorites-title.white-background.z-depth-1
    .col-md-12
      |Favorites
  - @favorites.each_with_index do |f, index|
    .row.favorites-row.white-background.z-depth-1
      .col-md-10.col-md-offset-1
       - f.places.each do |t|
        .col-md-2.favorites-element
          .favorite-name
            h5
              = t["name"]
          - if index < t.length - 1
            span
              i.fa.fa-toggle-right

app/views/user/new.html.slim
section
	.container.light-grey-background#user-form.z-depth-4
		h1.form-title.dark-grey-font
			|NEW USER
		h5.form-subtitle.dark-grey-font
			|Tell us a little about you
		= render 'form'

app/views/user/show.html.slim
section
	.container.light-grey-background#user-content
		.row
			#user-profile.col-md-12
				= render 'update'