config/routes.rb
Rails.application.routes.draw do
  # Root route
  root 'application#index'

  # Session routes
  post 'login', to: 'sessions#create', as: :login
  get 'logout', to: 'sessions#destroy', as: :destroy_session

  # Foursquare routes
  get 'suggestion/foursquare', to: 'foursquare#create_suggestion',
                               as: :foursquare_suggestion,
                               default: { format: 'js' }
  # User routes
  get '/user/new', to: 'user#new', as: :new_user
  post '/user/new', to: 'user#create', as: :create_user
  get '/user/show', to: 'user#show', as: :show_user
  patch 'user/update', to: 'user#update', as: :update_user
  get 'user/favorites', to: 'user#favorites', as: :favorites
  
  #DatePlans routes
  get '/dateplan', to: 'dateplan#show', as: :dateplan

  resources :dateplan
end

app/views/layouts/_footer.html.slim
footer.z-depth-3
  .container-fluid
    .row
      .col-md-4
        span.copyright
          | Wingman 2016
      .col-md-4.pull-right
        ul.list-inline.social-buttons.pull-right
          li
            a[href="https://twitter.com/awingmanproject"]
              i.fa.fa-twitter
          li
            a[href="#"]
              i.fa.fa-facebook

app/views/layouts/_login_modal.html.slim
div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
  div class="modal-dialog" style="width: 400px;"
    div class="modal-content"
      = simple_form_for :sessions, url: login_path, html: { class: 'form-vertical' } do |f|
        div class="modal-header"
          button type="button" class="close" data-dismiss="modal" aria-label="Close"
            span aria-hidden="true"
              |X
          h4 class="modal-title" id="myModalLabel" style="text-align: center;"
            |Login
        div class="modal-body"
          div class="row"
            div class="col-md-10 col-md-offset-1"
                = f.input :email, placeholder: 'Email', label: false 
                = f.input :password, placeholder: 'Password', label: false 
        div class="modal-footer"
          = f.submit class: "btn btn-md btn-primary", value: 'Login'
          '
          = link_to 'Sign up', new_user_path, class: 'btn btn-md btn-primary pull-left'

app/views/layouts/_nav.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'W', root_path, class: 'navbar-brand'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if current_user
          li
            = link_to 'Make Plans', dateplan_path, class: 'dark-grey-font'
          li
            = link_to 'Interests', show_user_path, class: 'dark-grey-font'
          li  
            = link_to 'Logout', destroy_session_path, id:'logout-btn', class: 'orange-font'
        li
        - if !current_user
          a.gray-font href="#" data-toggle="modal" data-target="#myModal" 
            | Login

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Wingman</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
</head>
<body>
	<%= render 'layouts/nav' %>
	<%= yield %>
	<%= render 'layouts/footer' %>
</body>
</html>